title: "TICS76"
description: "Este es el blog de apoyo para la clase de TICS"
about: "Este es el blog de apoyo para la clase de TICS"
location: "Mexico, CDMX"
email: marco.perez.cetis76@gmail.com
baseurl: ""
url: "http://marcoc76.github.io"
twitter_username: 
github_username:  marcoc76

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: es
close_btn: "Cerrar"
home_btn: "Inicio"
projects_btn: "Tutorias"
posts_btn: "Entradas"
imprint_btn: "Contacto"
name_badge: "Ing. Marco Antonio"
rss_badge: ""

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
